# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#home
    weight: 10
  - name: Schedule
    url: /#schedule
    weight: 20
  - name: Organizers
    url: /#organizers
    weight: 30
  - name: Resources
    url: /#resources
    weight: 40
  #   hasChildren: true
  # - parent: Resources
  #   name: Blog
  #   url: blog/
